// hey yall :3 (jesus loves u)
'use strict';

const REG_SKELETON_MAP = {
"local $A,$B,$C=$V,$V,$V;": "0",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$K[$B+#N]": "1",
"local $A,$B,$C=$V,$V,$V;for $V=$A,$A+$B do $R[$V+#N]=nil end": "2",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=($B~=#N);if $C~=#N then $IP=$IP+#N end": "3",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$R[$B+#N]": "4",
"local $A,$B,$C=$V,$V,$V;do local $V=$K[$B+#N];if $V[#N]==$V then $R[$A+#N]=$V[#N] else local $V=$V[$V];$R[$A+#N]=$V;$V[#N]=$V;$V[#N]=$V end end": "5",
"local $A,$B,$C=$V,$V,$V;do $V[$K[$B+#N]]=$R[$A+#N];$V[#N]=nil end": "6",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$R[$B+#N][$RK($C)]": "7",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N][$RK($B)]=$RK($C)": "8",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]={}": "9",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$RK($B)+$RK($C)": "10",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$RK($B)-$RK($C)": "11",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$RK($B)*$RK($C)": "12",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$RK($B)/$RK($C)": "13",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$RK($B)%$RK($C)": "14",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$RK($B)^$RK($C)": "15",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$V($RK($B)/$RK($C))": "16",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=-$R[$B+#N]": "17",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=not $R[$B+#N]": "18",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=#$R[$B+#N]": "19",
"local $A,$B,$C=$V,$V,$V;do if $C-$B<=#N then $R[$A+#N]=$R[$B+#N]..$R[$C+#N] else local $V={};for $V=$B,$C do $V[#$V+#N]=$R[$V+#N] end;$R[$A+#N]=$V($V) end end": "20",
"local $A,$B,$C=$V,$V,$V;$IP=$IP+$B*#N": "21",
"local $A,$B,$C=$V,$V,$V;if ($RK($B)==$RK($C))~=($A~=#N) then $IP=$IP+#N end": "22",
"local $A,$B,$C=$V,$V,$V;if ($RK($B)<$RK($C))~=($A~=#N) then $IP=$IP+#N end": "23",
"local $A,$B,$C=$V,$V,$V;if ($RK($B)<=$RK($C))~=($A~=#N) then $IP=$IP+#N end": "24",
"local $A,$B,$C=$V,$V,$V;if (not $R[$A+#N])==($C~=#N) then $IP=$IP+#N end": "25",
"local $A,$B,$C=$V,$V,$V;if (not $R[$B+#N])==($C~=#N) then $IP=$IP+#N else $R[$A+#N]=$R[$B+#N] end": "26",
"local $A,$B,$C=$V,$V,$V;do local $V=$R[$A+#N];local $V;if $B==#N then $V=$V($V()) elseif $B==#N then $V=$V($V($R[$A+#N])) elseif $B==#N then $V=$V($V($R[$A+#N],$R[$A+#N])) elseif $B==#N then $V=$V($V($V($R,$A+#N,$V))) else $V=$V($V($V($R,$A+#N,$A+$B))) end;if $C==#N then for $V=#N,$V.$V do $R[$A+$V]=$V[$V] end;$V=$A+$V.$V else for $V=#N,$C-#N do $R[$A+$V]=$V[$V] end end end": "27",
"local $A,$B,$C=$V,$V,$V;do local $V=$R[$A+#N];if $B==#N then return $V() elseif $B==#N then return $V($R[$A+#N]) elseif $B==#N then return $V($R[$A+#N],$R[$A+#N]) elseif $B==#N then return $V($V($R,$A+#N,$V)) else return $V($V($R,$A+#N,$A+$B)) end end": "28",
"local $A,$B,$C=$V,$V,$V;do if $B==#N then return $V($R,$A+#N,$V) elseif $B==#N then return else return $V($R,$A+#N,$A+$B-#N) end end": "29",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$R[$A+#N]-$R[$A+#N];$IP=$IP+$B*#N": "30",
"local $A,$B,$C=$V,$V,$V;do local $V=$R[$A+#N];local $V=$R[$A+#N]+$V;$R[$A+#N]=$V;local $V=$R[$A+#N];if $V>#N then if $V<=$V then $IP=$IP+$B*#N;$R[$A+#N]=$V end else if $V>=$V then $IP=$IP+$B*#N;$R[$A+#N]=$V end end end": "31",
"local $A,$B,$C=$V,$V,$V;do local $V=$R[$A+#N];local $V=$R[$A+#N];local $V=$R[$A+#N];local $V={$V($V,$V)};for $V=#N,$C do $R[$A+#N+$V]=$V[$V] end;if $V[#N]~=nil then $R[$A+#N]=$V[#N];$IP=$IP+#N end end": "32",
"local $A,$B,$C=$V,$V,$V;do local $V=$R[$A+#N];local $V=$B;if $V==#N then $V=$V-($A+#N) end;local $V=$C-#N;for $V=#N,$V do $V[$V+$V]=$R[$A+#N+$V] end end": "33",
"local $A,$B,$C=$V,$V,$V;do local $V=$V[$B+#N];if $V then local $V={};if $V.$V then for $V,$V in $V($V.$V) do if $V[#N]==#N then local $V;for $V=#N,#$V do if $V[$V][#N]==$V[#N]+#N then $V=$V[$V];break end end;if not $V then $V={$R,$V[#N]+#N};$V[#$V+#N]=$V end;$V[$V]=$V else $V[$V]=$V[$V[#N]+#N] end end end;$R[$A+#N]=function(...) return $V($V.$K,$V.$C,$V.$V,$V.$V and $V or {},$V.$V,$V.$V,$V.$V,$V,...) end else $R[$A+#N]=nil end end": "34",
"local $A,$B,$C=$V,$V,$V;do if $B==#N then for $V=#N,$V do $R[$A+$V]=$V[$V] end;$V=$A+$V else for $V=#N,$B-#N do $R[$A+$V]=$V[$V] end end end": "35",
"local $A,$B,$C=$V,$V,$V;$R[$A+#N]=$R[$B+#N];$R[$A+#N]=$R[$B+#N][$RK($C)]": "36",
"local $A,$B,$C=$V,$V,$V;do local $V=$V[$B+#N];if $V[#N] then $R[$A+#N]=$V[#N][$V[#N]] else $R[$A+#N]=$V[#N] end end": "37",
"local $A,$B,$C=$V,$V,$V;do local $V=$V[$B+#N];if $V[#N] then $V[#N][$V[#N]]=$R[$A+#N] else $V[#N]=$R[$A+#N] end end": "38",
"local $A,$B,$C=$V,$V,$V;do local $V=#N;for $V=#N,#$V do local $V=$V[$V];if $V[#N]>=$A+#N then $V[#N]=$V[#N][$V[#N]];$V[#N]=nil else $V=$V+#N;$V[$V]=$V end end;for $V=$V+#N,#$V do $V[$V]=nil end end": "39",
"local $A,$B,$C=$V,$V,$V;do local $V=$R[$A+#N];local $V;if $B==#N then $V=$V($V($V)) elseif $B==#N then $V=$V($V($V,$R[$A+#N])) elseif $B==#N then $V=$V($V($V,$R[$A+#N],$R[$A+#N])) else $V=$V($V($V,$V($R,$A+#N,$A+$B))) end;if $C==#N then for $V=#N,$V.$V do $R[$A+$V]=$V[$V] end;$V=$A+$V.$V else for $V=#N,$C-#N do $R[$A+$V]=$V[$V] end end end": "40",
"local $A,$B,$C=$V,$V,$V;do local $V=$R[$A+#N];local $V=$R[$A+#N];local $V;if $B<=#N then $V=$V($V($V,$V)) elseif $B==#N then $V=$V($V($V,$V,$R[$A+#N])) else $V=$V($V($V,$V,$V($R,$A+#N,$A+$B))) end;if $C==#N then for $V=#N,$V.$V do $R[$A+$V]=$V[$V] end;$V=$A+$V.$V else for $V=#N,$C-#N do $R[$A+$V]=$V[$V] end end end": "41",
"local $A,$B,$C=$V,$V,$V;do local $V=$R[$A+#N];if $V($V)==\"$V\" then local $V,$V=$V($V,$V);if $V and $V($V)==\"$V\" and $V.$V then $R[$A+#N]=$V.$V($V) else $R[$A+#N]=$V;$R[$A+#N]=$V;$R[$A+#N]=nil end end end": "42",
"local $A,$B,$C=$V,$V,$V;local $V=$CODE[$IP+#N];$R[$A+#N]=$K[$V+#N];$IP=$IP+#N": "43",
"local $A,$B,$C=$V,$V,$V;do local $V=$CODE[$IP+#N];if (not $R[$A+#N])~=($C~=#N) then $IP=$IP+#N+$V*#N else $IP=$IP+#N end end": "45",
"local $A,$B,$C=$V,$V,$V;do local $V,$V=$RK($B),$RK($C);local $V=$CODE[$IP+#N];if ($V==$V)~=($A~=#N) then $IP=$IP+#N else $IP=$IP+#N+$V*#N end end": "46",
"local $A,$B,$C=$V,$V,$V;do local $V,$V=$RK($B),$RK($C);local $V=$CODE[$IP+#N]*#N;$IP=$IP+#N;if ($V<$V)==($A~=#N) then $IP=$IP+$V end end": "47",
"local $A,$B,$C=$V,$V,$V;do local $V=$CODE[$IP+#N];if ($RK($B)<=$RK($C))==($A~=#N) then $IP=$IP+#N+$V*#N else $IP=$IP+#N end end": "48",
"local $A,$B,$C=$V,$V,$V;do local $V=$CODE[$IP+#N];if (not $R[$B+#N])==($C~=#N) then $IP=$IP+#N else $R[$A+#N]=$R[$B+#N];$IP=$IP+#N+$V*#N end end": "49",
"local $A,$B,$C=$V,$V,$V;do local $V=$CODE[$IP+#N];local $V=$CODE[$IP+#N];local $V=$V[$K[$B+#N]];$R[$A+#N]=$V;$R[$V+#N]=$V[$RK($V)];$IP=$IP+#N end": "50",
"local $A,$B,$C=$V,$V,$V;do local $V=$CODE[$IP+#N];local $V=$CODE[$IP+#N];$R[$A+#N]=$K[$B+#N];$R[$V+#N]=$K[$V+#N];$IP=$IP+#N end": "51",
"local $A,$B,$C=$V,$V,$V;do $R[$A+#N]=$R[$B+#N];$R[$CODE[$IP+#N]+#N]=$R[$CODE[$IP+#N]+#N];$IP=$IP+#N end": "52",
"local $A,$B,$C=$V,$V,$V;do $R[$A+#N]=$R[$B+#N];local $V=$R[$B+#N][$RK($C)];$R[$A+#N]=$V;local $V=$CODE[$IP+#N];local $V=$CODE[$IP+#N];$IP=$IP+#N;local $V;if $V==#N then $V=$V($V($R[$A+#N])) elseif $V==#N then $V=$V($V($R[$A+#N],$R[$A+#N])) elseif $V==#N then $V=$V($V($V($R,$A+#N,$V))) else $V=$V($V($V($R,$A+#N,$A+$V))) end;if $V==#N then for $V=#N,$V.$V do $R[$A+$V]=$V[$V] end;$V=$A+$V.$V else for $V=#N,$V-#N do $R[$A+$V]=$V[$V] end end end": "53",
"local $A,$B,$C=$V,$V,$V;do local $V=$CODE[$IP+#N];local $V=$CODE[$IP+#N];local $V=$CODE[$IP+#N];local $V=$CODE[$IP+#N];local $V=$CODE[$IP+#N];local $V=$V[$K[$B+#N]];$R[$A+#N]=$V;$R[$V+#N]=$V[$RK($V)];local $V=$R[$V+#N];$IP=$IP+#N;local $V;if $V==#N then $V=$V($V()) elseif $V==#N then $V=$V($V($R[$V+#N])) elseif $V==#N then $V=$V($V($R[$V+#N],$R[$V+#N])) elseif $V==#N then $V=$V($V($V($R,$V+#N,$V))) else $V=$V($V($V($R,$V+#N,$V+$V))) end;if $V==#N then for $V=#N,$V.$V do $R[$V+$V]=$V[$V] end;$V=$V+$V.$V else for $V=#N,$V-#N do $R[$V+$V]=$V[$V] end end end": "54",
"local $A,$B,$C=$V,$V,$V;do $R[$A+#N]=$K[$B+#N];$IP=$IP+#N;return $R[$A+#N] end": "55",
"local $A,$B,$C=$V,$V,$V;do local $V=$CODE[$IP+#N];local $V=$CODE[$IP+#N];$R[$A+#N]=$R[$B+#N];$IP=$IP+#N;if $V==#N then return $V($R,$V+#N,$V) elseif $V==#N then return else return $V($R,$V+#N,$V+$V-#N) end end": "56",
};
module.exports = { REG_SKELETON_MAP };
